#define PROJECT_VERSION_MAJOR	"@PROJECT_VERSION_MAJOR@";
#define PROJECT_VERSION_MINOR	"@PROJECT_VERSION_MINOR@";
#define PROJECT_VERSION_PATCH	"@PROJECT_VERSION_PATCH@";
#define CMAKE_HOST_SYSTEM	"@CMAKE_HOST_SYSTEM@";
#define CMAKE_CXX_COMPILER_ID	"@CMAKE_CXX_COMPILER_ID@";
#define CMAKE_CXX_COMPILER_VERSION	"@CMAKE_CXX_COMPILER_VERSION@";
#define CMAKE_BUILD_TYPE	"@CMAKE_BUILD_TYPE@";